### ISSUE TITLE
program crashed when trying to 

### ISSUE THREAD

**Issue by piflixe** [jethornton/7i95#1]
Whenever I try to configure the spindle using the "Spindle" tab the program crashes.

I tried Version 0.1.0 and 0.1.1 of the provided .deb packages. I also tried with an empty configuration, with everything else already set up and with a mesa card connected.

I am using the LinuxCNC 2.8 release from the .iso image (currentyl 2.8.2-11-g6a3d0a434). Python 3.7 is installed as well as mesaflash tool.

**Comment by piflixe** [comment]
Unfortunately, I am not a good programmer so can't really change the code myself. But I am willing to run further testing, improve documentation etc.

**Comment by jethornton** [comment]
Sorry been a bit busy and have not checked here.

JT

**Comment by jethornton** [comment]
This has been fixed

**Comment by piflixe** [comment]
> This has been fixed

confirmend! thank you very much
