### ISSUE TITLE
[BUG] Tool exits itself

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/7i95#11]
-- en -- 
1. i can't call my machine anymore. 
2. when I create a new machine, the program closes itself.
2.1 Configurations Name == OK 
2.2 Linear Units == OK (mm) 
2.3 Max Linear Velocity == Program closes itself.

I have enclosed my configuration folder.
Machine can be started in LinuxCNC 2.8. 

-- de -- 
1. ich kann meine Maschine nicht mehr aufrufen. 
2. Wenn ich eine Neue Maschine anlege, schließt das Programm sich selbst.
2.1 Configurations Name == OK 
2.2 Linear Units == OK (mm) 
2.3 Max Linear Velocity == Programm Schließt sich selbst.

Meinen Konfigurationsordner habe ich beigelegt.
Maschine lässt sich in LinuxCNC 2.8 Starten 

[x-achse.zip](https://github.com/jethornton/7i95/files/8549698/x-achse.zip)

**Comment by jethornton** [comment]
It is more helpful if you run from a terminal when you encounter problems and copy the text from the terminal as well.

**Comment by M-u-e-c-k-e** [comment]
Start and load my INI (X-Achse) 
```
cnc@DebianCNC:~$ 7i95
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lib7i95/utilities.py", line 77, in maxVelChanged
    parent.maxVelMinLB.setText(F'{val * 60} units/min')
AttributeError: 'MainWindow' object has no attribute 'maxVelMinLB'
Abgebrochen
cnc@DebianCNC:~$ 
```
I did not know that an error message is given with out.
I have learned something again.

Start and create a new configuration:
```
cnc@DebianCNC:~$ 7i95
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lib7i95/utilities.py", line 77, in maxVelChanged
    parent.maxVelMinLB.setText(F'{val * 60} units/min')
AttributeError: 'MainWindow' object has no attribute 'maxVelMinLB'
Abgebrochen
cnc@DebianCNC:~$ 
```

**Comment by M-u-e-c-k-e** [comment]
-- en -- 
Installed the new version. 
Tool still exits :-( 

-- de -- 
Habe die Neue Version Installiert. 
Tool beendet sich immer noch :-( 
```
$ 7i95
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lib7i95/loadini.py", line 45, in openini
    loadini(parent, iniFile)
  File "/usr/lib/python3/dist-packages/lib7i95/loadini.py", line 157, in loadini
    if isinstance(getattr(parent, item[2]), QLabel):
AttributeError: 'MainWindow' object has no attribute 'maxLinearVel'
Abgebrochen
```
