### ISSUE TITLE
config not workgin: check_config ERROR

### ISSUE THREAD

**Issue by piflixe** [jethornton/7i95#2]
I tried to set up the 7i95 for my machine and get the following error when trying to start linuxCNC Version 2.8.2-11-g6a3d0a434 with this config: 
```
check_config: (trivkins kinematics) WARNING:
  Unspecified [AXIS_P]MIN_LIMIT,        default used: -1e99
  Unspecified [AXIS_P]MAX_LIMIT,        default used: +1e99
  Unspecified [AXIS_A]MIN_LIMIT,        default used: -1e99
  Unspecified [AXIS_A]MAX_LIMIT,        default used: +1e99
  Unspecified [AXIS_{]MIN_LIMIT,        default used: -1e99
  Unspecified [AXIS_{]MAX_LIMIT,        default used: +1e99
  INCONSISTENT coordinates specifications:
               trivkins coordinates=\{PARENT.COORDINATESLB.TEXT()\}
               [TRAJ]COORDINATES=XYZ


check_config: (trivkins kinematics) ERROR:
  [JOINT_1]MIN_LIMIT > [AXIS_P]MIN_LIMIT (-1 > -1e99)
  [JOINT_1]MAX_LIMIT < [AXIS_P]MAX_LIMIT (280 < +1e99)
  [JOINT_2]MIN_LIMIT > [AXIS_A]MIN_LIMIT (-1 > -1e99)
  [JOINT_2]MAX_LIMIT < [AXIS_A]MAX_LIMIT (170 < +1e99)
  [JOINT_0]MIN_LIMIT > [AXIS_{]MIN_LIMIT (-1 > -1e99)
  [JOINT_0]MAX_LIMIT < [AXIS_{]MAX_LIMIT (612 < +1e99)

```

**Comment by piflixe** [comment]
I got a bit confused about several thinks:
* how I read the documentation, MIN_LIMIT / MAX_LIMIT should be defined for the joints. Currently the entries appear in the [AXIS_n] and [JOINT_n] sections
* I think in the [KINS] section `KINEMATICS = trivkins coordinates={parent.coordinatesLB.text()}` a variable is not parsed correctly and should be `KINEMATICS = trivkins coordinates=XYZ`
* the homing settings put in the config tool (Axis tab -> Joint n -> Homing) are not saved to the .ini output file

However, changing all of the above did not make the config work so I don't know if the problems are related or not. Please let me know if I should open seperate issues for them.

**Comment by jethornton** [comment]
Post your ini file as an attachment. I don't have a 7i95 in stock due to the shortage so I can't test.

I know about the homing options as I had the same thing in my 7i96 tool and will address that in the morning.

JT

**Comment by jethornton** [comment]
KINEMATICS = trivkins coordinates={parent.coordinatesLB.text()} has been fixed

JT

**Comment by jethornton** [comment]
The tool will now make a working configuration thanks to PCW for sending me a card to test with.

JT
