### ISSUE TITLE
[IDEE] Update in menu 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/7i95#7]
-- EN -- 
Hello, 

is it possible to add an update button in the menu? 
So that an update can be started manually from the software? 

Greetings 

-- DE -- 
Hallo, 

ist es möglich einen Update Knopf im Menü anzubringen? 
So das Manuell ein Update aus der Software Heraus gestartet werden kann? 

Gruß

**Comment by jethornton** [comment]
It might be possible but I don't know how.

**Comment by M-u-e-c-k-e** [comment]
-- EN -- 
I don't know anything about this :-(, I don't program. 

Now that I think about it, can't you use the terminal to download data and save it in one place? 
Your program knew where it was installed? can't you just overwrite the data? 

As I said I do not know anything about it.

-- DE -- 
ich kenne mich damit nicht aus :-(, ich programmiere nicht. 

Wenn ich so drüber nachdenke, kann man über das Terminal nicht Daten Downloaden und an einem Ort Speichern lassen? 
Dein Programm wies wo es Installiert ist?  kann man dann nicht einfach die Daten überschreiben? 

Wie gesagt ich kenne mich damit nicht aus.

**Comment by jethornton** [comment]
When the program is running it knows where it is in the directory tree, however if it's a deb that's been installed and a new version has been make it takes sudo power and some magic to upgrade. It "might" be possible to update if running from a terminal but that would not update the running program. Just complicates everything more than needed. If you cloned the repo then open a terminal in the base directory and do git pull again. You have to close the program to update in any case.

**Comment by M-u-e-c-k-e** [comment]
-- DE -- 
Ah Ok, ich verstehe die Problematik. 

Jetzt verstehe ich auch warum Programme sich schlissen und neu Starten wenn sie ein Update machen. 
Bei Windows muss ich bei Updates auch oft (nicht immer) mein Passwort eingeben, ich finde das Normal. 

Es war nur ein IDEE, wenn nicht machbar oder zum Aktuellen Zeitpunkt nicht machbar dann kann das Ticket ja geschlossen werden?

**Comment by jethornton** [comment]
I think it's best to leave it open in case a solution is found that makes this feasible.

JT

**Comment by jethornton** [comment]
I did figure out how to check to see if your running the latest version and added that

**Comment by M-u-e-c-k-e** [comment]
-- EN --
 This is good news. I am looking forward to test it. I still have version 1.1.0 ;-) 

-- DE -- 
Das sind gute Nachrichten. Ich freue mich darauf es zu testen. Noch habe ich Version 1.1.0 ;-)

**Comment by jethornton** [comment]
I fixed a typo and added a download deb button

**Comment by M-u-e-c-k-e** [comment]
-- en -- 
OK, I tried to install it, but I can't start the program anymore ;-( 
Where is it installed? 
I want to uninstall everything!
Then reinstall. 

I do not know so well with it. 

-- de -- 
OK, ich habe es versucht zu Installieren, ich kann das Programm gar nicht mehr Starten. ;-( 
Wo ist das Installiert? 
Ich möchte alles Deinstallieren!
Danach neu Installieren. 

Ich kenne mich damit nicht so gut aus.

**Comment by jethornton** [comment]
What is 19.04?
What error did you get?

**Comment by M-u-e-c-k-e** [comment]
_What is 19.04?_ this is the date ;-) 19.04.2022
_What error did you get?_ none at all, it simply does not start. 


_Edit: I see I need to add packaging to the requirements so that package is pulled in._
:-), then I can test it later?

**Comment by jethornton** [comment]
Did you try running from the command line in a terminal?

**Comment by M-u-e-c-k-e** [comment]
-- en -- 
how do you do that? 

-- de -- 
wie macht man das?

**Comment by jethornton** [comment]
open a terminal and type 7i95

**Comment by M-u-e-c-k-e** [comment]
:-) it can be as simple as that. 
I get an error message: 

![grafik](https://user-images.githubusercontent.com/103420027/164468788-ef1e49e2-cead-4f1f-afad-37ef5dfab131.png)

Text: 
> $ 7i95
> Traceback (most recent call last):
>   File "/usr/bin/7i95", line 28, in <module>
>     from lib7i95 import utilities
>   File "/usr/lib/python3/dist-packages/lib7i95/utilities.py", line 1, in <module>
>     import os, subprocess, requests
> ModuleNotFoundError: No module named 'requests'

**Comment by jethornton** [comment]
Download and reinstall the deb and all depends should be satisfied

**Comment by M-u-e-c-k-e** [comment]
-- en -- 
Perfect, it starts again. 
Tried to make an update. Answer came twice: 
> The Repo version 1.1.0 is the same as this version

I am very impressed with you and your program, keep up the good work! 

-- de -- 
Perfekt, es startet wieder. 
Habe versucht ein Update zu machen. Antwort ist Doppelt gekommen: 
> The Repo version 1.1.0 is the same as this version

Ich bin sehr beeindruckt von dir und deinem Programm, mach weiter so!
